tasks:
  - init: pipenv install
  - command: pipenv shell uvicorn api.main:app --reload

ports:
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - mkaufman.HTMLHint@0.6.0:TdNYbCmjW8N3yiaPW4/adg==
    - mathiasfrohlich.Kotlin@1.7.1:2Uw0hH38NcpgInldjuwF3g==
    - ronnidc.nunjucks@0.2.3:WQVPscP5AsQ+pBtpJtRDWQ==
    - ms-vscode-remote.remote-ssh-edit@0.50.1:fzQqpXhhL16UVNSAdMLAZg==
    - yrpark99.hex-ascii-converter@0.0.1:1PcG8r2ZYnUsKgd6qAUB2Q==
    - marioterron.one-dark-bimbo@1.2.0:ddhkv1NinfcV8SxZCxu76g==
    - abusaidm.html-snippets@0.2.1:7b7Vkkp6Lem9WOqKCYMq2w==
    - ms-vscode-remote.remote-wsl@0.42.4:+lzjZGzRtNoMwCfHMMLcUA==
    - christian-kohler.path-intellisense@1.4.2:QnOrf5fk6KiVaQs4cNEP+w==
    - 2gua.rainbow-brackets@0.0.6:Tbu8dTz0i+/bgcKQTQ5b8g==
    - humao.rest-client@0.23.2:EcQzdx/LsXrhATjZFVSutw==
    - christian-kohler.npm-intellisense@1.3.0:yQtCdwoyo890Bn9NOEuEDA==
    - mikey.vscode-fileheader@0.0.2:HcJskKjAtcOS7n+3OPtHvQ==
    - marcostazi.VS-code-vagrantfile@0.0.7:IdmAveYqd/Ne5VDWx/61Ew==
    - bbenoist.vagrant@0.5.0:e2ktoGsnar8weYYRNdvexg==
    - Equinusocio.vsc-material-theme@32.5.0:QKQzJamqCIUjkJSSXc5o8w==
    - zhuangtongfa.material-theme@3.2.4:VM7fGP3u8tH+WIxtPVRKiA==
    - dbaeumer.vscode-eslint@2.1.1:DO6k4GCpqhwZcKo+jY9xjQ==
    - Equinusocio.vsc-community-material-theme@1.4.1:2d15NVwWyYQcMHTXW/HKyw==
    - ryu1kn.partial-diff@1.4.1:a/nnA3Dp2+Bai+u2GS4uNw==
    - ms-vscode-remote.remote-ssh@0.50.1:5m/MTLliaPjRU9J7Wsbwuw==
    - dracula-theme.theme-dracula@2.21.0:RtzqaQieYebr5vxh8cZ+pQ==
    - eg2.tslint@1.0.44:3C/9/4VxeLePYcf3QXEZsQ==
    - ecmel.vscode-html-css@0.2.3:RBTpzQbz8rn5KTlc82tnsQ==
    - donjayamanne.githistory@0.6.3:ulyoBfbnPc13dUJlJRY16w==
    - sleistner.vscode-fileutils@3.0.1:z8IOIjJJXH4lAgoLexBPxQ==
    - ms-azuretools.vscode-docker@1.0.0:o4JHmJJeh+tjjl4bEqFtqg==
    - formulahendry.auto-close-tag@0.5.6:oZ/8R2VhZEhkHsoeO57hSw==
    - Shan.code-settings-sync@3.4.3:lADxYq3EKc+4gqNNppMuiQ==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - formulahendry.auto-rename-tag@0.1.1:lKCmLIZAiCM0M8AjDnwCLQ==
    - akamud.vscode-theme-onelight@2.2.0:QqSCGFEi/a045aS1VOXdJw==
    - spywhere.guides@0.9.3:+als4CFIGPiS7/FIjW9xfg==
    - eg2.vscode-npm-script@0.3.11:peDPJqeL8FmmJiabU4fAJQ==
    - HookyQR.beautify@1.5.0:mXo/OcopUVNHHxCPZWwlxQ==
    - PKief.material-icon-theme@4.0.1:uW65d0I1ibFxFDWPtc2zkQ==
    - alefragnani.project-manager@10.11.0:9cZC+FN3RCkVIXPE7gt+ZQ==
    - slevesque.vscode-hexdump@1.7.2:tUgBu4YhnZF5BgOhGqSlbA==
    - oysun.vuehelper@0.1.0:D2uJwU7fAsdq074hhCkKOA==
    - Orta.vscode-jest@3.1.1:LQ3p9BsZrD/DSsU8zMC01g==
    - equinusocio.vsc-material-theme-icons@1.1.4:X+AVKGzKKgifhbKfaJ2aSQ==
    - johnpapa.winteriscoming@1.4.1:nvPCrQDS+aIC2lsnBlpG0A==
    - EditorConfig.EditorConfig@0.14.4:EjFaoTaOf8wRmwR0LNY51A==
    - felipecaputo.git-project-manager@1.7.1:oJt/Fy6hZ37P9NnY40Rikg==
    - formulahendry.code-runner@0.9.17:/CI2LS8o4IE980vinLu1Yg==
    - teabyii.ayu@0.18.0:43zsEDFuC6dcxhBPBJlJlg==
    - naumovs.color-highlight@2.3.0:6nKORbxgnWjNaN6xACiaQQ==
    - CoenraadS.bracket-pair-colorizer@1.0.61:fqPT1sJEqaEdrfXeYbdW+A==
    - eamodio.gitlens@10.2.1:e0IYyp0efFqVsrZwsIe8CA==
    - mkxml.vscode-filesize@2.1.3:NUBIRSmJbN5RuR/xPxJVCQ==
    - felixfbecker.php-intellisense@2.3.14:3tN5FICV5G1FtmHuI0yDWw==
    - eyhn.vscode-vibrancy@1.0.9:5B7Dehl1AuSgTxBGu8QrWg==
    - msjsdiag.debugger-for-chrome@4.12.6:S9ct7J+XIe9f82CdPpLyWw==
    - oderwat.indent-rainbow@7.4.0:nth8lnJRnQu9NcWvNc9KPA==
    - Zignd.html-css-class-completion@1.19.0:b3YWQQIEP1z3u93nyLX0UA==
    - ms-vscode.cpptools@0.26.3:u3GsZ5PK12Ddr79vh4TWgQ==
    - ms-vscode.Go@0.13.1:MNyp3peDBlBzsVL8F0+e+A==
    - naco-siren.gradle-language@0.2.3:zC8GEZcOCPVruGnbzEEMFQ==
    - hyb1996.auto-js-vscodeext@0.2.3:QqidhmtpIE9tCR05zB+25g==
    - ms-vscode.powershell@2020.3.0:H/4y4xSFVRgnA+6ETxlhEg==
    - redhat.java@0.58.0:6QTFHCiUMvEe2MuJ4Uwwkw==
    - ms-python.python@2020.3.69010:EKtH+UAhoON/xBRkiNao1Q==
    - wix.vscode-import-cost@2.12.0:Z31eYgMsqJCLYkcg0s66Ug==
    - vscoss.vscode-ansible@0.5.2:Mff9FZmh2X9uPnMB9kEzCA==
    - octref.vetur@0.24.0:wQwUWmMBrV2Y+ZN1GPaapg==
